### ISSUE TITLE
banana

### ISSUE THREAD

**Issue by reiyua** [johannesmu/firstwebsite24#1]
![minion banana](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNXR1N2M1bndiN2hxd3QwbGVmcTM5OTl0azcyNGY2Zzg4dnJtYmNnOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1uPiL9Amv5zkk/giphy.gif)

-Ray

**Comment by johannesmu** [comment]
Issue closed no infringing banana found

**Comment by reiyua** [comment]
![minion sad](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnYxMzdzMGRmM3ZkaXVpYWw1djZ3MGQ5bzM4bjQzbmdndHF6aWxhaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/K4tZWT1upee6Q/giphy.gif)

Bob does not approve.
